### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by swapnil-athawale** [robeljc/afronet#1]
When accessing the google drive link , it is Not able to send  access request

**Comment by mrboxtobox** [comment]
Sorry about that. You can find the dataset here (data.zip, 3GB): https://drive.google.com/open?id=13PLsc5jIgHw0hvMnR9aM4LGLvELCZKNS

Please reopen if you have more questions and, if you end up using the dataset, please don't forget to cite the project. Thank you.
